# Generated by Django 4.2.6 on 2023-10-14 21:25

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_potterycategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='home.potterycategory'),
        ),
    ]
