# Generated by Django 4.2.6 on 2024-06-02 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homecarousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecarousel',
            name='hero_text',
            field=models.CharField(default=datetime.datetime(2024, 6, 2, 18, 25, 45, 512254, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
    ]
