# Generated by Django 4.2.6 on 2024-06-02 18:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('home', '0008_homecarousel_hero_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecarousel',
            name='hero_cta',
            field=models.CharField(default=datetime.datetime(2024, 6, 2, 18, 56, 38, 8761, tzinfo=datetime.timezone.utc), help_text='Text to display on Call to Action', max_length=255, verbose_name='Hero CTA'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homecarousel',
            name='hero_cta_link',
            field=models.ForeignKey(blank=True, help_text='Choose a page to link to for the Call to Action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Hero CTA link'),
        ),
    ]
